### ISSUE TITLE
how about the clblast-llama performance?

### ISSUE THREAD

**Issue by caofx0418** [lperezmo/clblast-llama-cpp-python#1]
how about the clblast-llama performance?
Unfortunately, In my test, it worse than only CPU. CPU is 8tokens/s，but this is only 2tokens/s.

**Comment by lperezmo** [comment]
Hi there, for me it seems to increase it from 4-5 t/s to around 6-7 t/s, but you have to be careful not too offload too many layers to GPU, otherwise performance starts to degrade. For example, for my RX5500M (4 gb), the ideal number of layers seems to be 15.

I think the reason is because if too many layers are offloaded to the GPU, then the GPU has to swap data in and out of its memory, which slows it down. I keep track of it with task manager.

Here are some screenshots I took from llama2 7b.

--------
*without clblast* **(4.69 t/s)**
![image](https://github.com/lperezmo/clblast-llama-cpp-python/assets/61613934/fd3a1852-45b0-4c2f-836b-6ce012ed6455)

--------
*with clblast - 15 layers* **(6.37 t/s)**
![image](https://github.com/lperezmo/clblast-llama-cpp-python/assets/61613934/34b6e9b6-15ad-46b5-8cfb-00af03cd7403)

--------
So the gains are not nearly as high as they would be with, let's say CUDA, or for newer AMD GPUs with ROCm. If you have a similar infrastructure to the ROCm then it might work if you assign it, like `HSA_OVERRIDE_GFX_VERSION=10.3.0`.


In the end, if you have the money then get an nvidia GPU or laptop with an nvidia GPU, that's a solid bet.
